apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: snginx 
  labels:
    name: expense
spec:
  containers:
  - name: nginx
    image: nginx


