apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec:
  type: NodePort
  selector:
    name: expense
    demo: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

---
apiVersion: v1
kind: Pod
metadata:
  name: nodenginx 
  labels:
    name: expense
    demo: node
spec:
  containers:
  - name: nginx
    image: nginx


