kind: Service
apiVersion: v1
metadata:
  name: nginx-lp
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lp
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lp
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lp
spec:
  containers:
  - name: nginx
    image: nginx
    