apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-dp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dp
  template:
    metadata:
      labels:
        app: nginx-dp
    spec:
      containers:
      - name: nginx
        image: manjudbadevops/deployment:1.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

