apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: efs-pv
  resources:
    requests:
      storage: 5Gi

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-efs
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    project: expense
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim


